### ISSUE TITLE
Search requests are all failing with 401 unauthorized

### ISSUE THREAD

**Issue by mturley** [n8j1s/Discogs-ObjC#3]
It seems like the search requests this library seems to support require authentication with Discogs.  Is there any way I can authenticate so my requests will work, or was this requirement introduced after the development of this library (a breaking change)?

Thanks!

**Comment by maxep** [comment]
Hello,

Just to let you know that Discogs has introduced the [Discogs Auth](http://www.discogs.com/developers/#page:authentication) which is a way easier to integrate than the OAuth if you only plan to use database's endpoints.

**Comment by n8j1s** [comment]
finally got around to adding support for Discogs Auth!
