### ISSUE TITLE
How to authenticate using consumer key and secret?

### ISSUE THREAD

**Issue by yoasha** [n8j1s/Discogs-ObjC#6]
Hi,
How can I use the library to authenticate using consumer key and secret?

Currently I can see only one option using DCDiscogsApiConfiguration class of setUserAgent:andTokenString:

Thank you!

**Comment by n8j1s** [comment]
If you look at my last commit, you can duplicate the code in dcdiscogsapiconfiguration to create a second constructor passing in consumer key and secret. The change the DCDiscogsHttpManager to add the appropriate http headers to each request. Quite simple to implement. I welcome pull requests!

**Comment by yoasha** [comment]
Thanks!
